apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: nginx
        image: 707913648704.dkr.ecr.us-east-1.amazonaws.com/service-a:1.0
        ports:
        - containerPort: 80
