apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cluster2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nonsocha/Gittops-cluster.git
    targetRevision: HEAD
    path: my-app/service-a
  destination:
    server: https://A95625E88BDAD64C149DCA04C52B3DD8.gr7.us-east-1.eks.amazonaws.com
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
